version: '3.8'

services:
  ravenDb:
    image: ravendb/ravendb
    restart: always
    ports:
      - 8080:8080
    volumes:
      - configVolume:/opt/RavenDB/config
      - dataVolume:/opt/RavenDB/Server/RavenData
    environment:
      RAVEN_ARGS: --ServerUrl=http://0.0.0.0:8080 --Setup.Mode=None --License.Eula.Accepted=true
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'

volumes:
  configVolume:
  dataVolume:

