version: '3.8'

services:
  ravenDb:
    image: ravendb/ravendb
    restart: always
    ports:
      - 8080:8080
    volumes:
      - configVolume:/opt/RavenDB/config
      - dataVolume:/opt/RavenDB/Server/RavenData
    environment:
      RAVEN_ARGS: '--Setup.Mode=None'
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'
      RAVEN_License_Eula_Accepted: 'true'
  
  postgreSQL:
    container_name: pg_container
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CthulhuWizardUsers
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  configVolume:
  dataVolume:
  pgdata: