name: .NET

on:
  pull_request:
    branches: [ develop ]
    
defaults:
      run:
        working-directory: ./CthulhuWizard/CthulhuWIzard.API

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal CthulhuWizardAPI/CthulhuWizard/CthulhuWizard.Tests.Unit/CthulhuWizard.Tests.Unit.csproj
    - name: Integration Test
      run: dotnet test --no-build --verbosity normal CthulhuWizardAPI/CthulhuWizard/CthulhuWizard.Tests.Integrations/CthulhuWizard.Tests.Integrations.csproj
